[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

# Generate real-time logs using script
[INPUT]
    Name   exec
    Command /fluent-bit/etc/generate-logs.sh
    Tag    kube.api
    Interval_Sec 1

[FILTER]
    Name   lua
    Match  kube.*
    Script enrich.lua
    Call   enrich_log

[FILTER]
    Name   parser
    Match  kube.*
    Key_Name  log
    Parser    k8s_log
    Reserve_Data On

[OUTPUT]
    Name   stdout
    Match  kube.*
    Format json_lines

[OUTPUT]
    Name            http
    Match           kube.*
    Host            cloudwatch-local-service
    Port            4588
    URI             /loki/api/v1/push
    Header          Content-Type application/json
    Format          json
    Json_date_key   ts
    Json_date_format iso8601
    json_date_key __timestamp
    json_date_format iso8601
