{{- if .Values.cloudwatchService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudwatch-log-persist.fullname" . }}
  labels:
    {{- include "cloudwatch-log-persist.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudwatch-service
spec:
  type: {{ .Values.cloudwatchService.service.type }}
  ports:
    - port: {{ .Values.cloudwatchService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudwatch-log-persist.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cloudwatch-service
{{- end }}
