{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudwatch-log-persist.fullname" . }}-postgres-secret
  labels:
    {{- include "cloudwatch-log-persist.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
{{- end }}
{{- if and (not .Values.postgres.enabled) (not .Values.postgres.external.existingSecret) .Values.postgres.external.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudwatch-log-persist.fullname" . }}-external-postgres-secret
  labels:
    {{- include "cloudwatch-log-persist.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  password: {{ .Values.postgres.external.password | quote }}
{{- end }}
---
{{- if and .Values.minio.enabled (not .Values.minio.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudwatch-log-persist.fullname" . }}-minio-secret
  labels:
    {{- include "cloudwatch-log-persist.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.auth.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.auth.rootPassword | quote }}
{{- end }}
{{- if and (not .Values.minio.enabled) (not .Values.minio.external.existingSecret) (or .Values.minio.external.accessKey .Values.minio.external.secretKey) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudwatch-log-persist.fullname" . }}-external-minio-secret
  labels:
    {{- include "cloudwatch-log-persist.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  {{- if .Values.minio.external.accessKey }}
  aws-access-key-id: {{ .Values.minio.external.accessKey | quote }}
  {{- end }}
  {{- if .Values.minio.external.secretKey }}
  aws-secret-access-key: {{ .Values.minio.external.secretKey | quote }}
  {{- end }}
{{- end }}
