apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://cloudwatch-local-service:4588
    isDefault: true
    editable: true

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      authType: keys
      defaultRegion: us-east-1
      endpoint: http://cloudwatch-local-service:4588
    secureJsonData:
      accessKey: dummy
      secretKey: dummy
    editable: true